server:
  port: 0
spring:
  application:
    name: order-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  cloud:
#    openfeign:
#      circuitbreaker:
#        enable: true
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      productService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        record-failure-predicate: com.example.order_service.client.circuitbreaker.ExceptionRecordFailurePredicate

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

