pipeline {
    agnet any

    environment {
        MY_NETWORK = "buynest-network"
        DOCKER_IMAGE = "product-service"
        DOCKER_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('product-service') {
                    script {
                        sh "chmod +x gradlew"
                        sh "./gradlew clean build"
                        archiveArtifacts artifacts: 'build/api-spec/*.json', allowEmptyArchive: false
                    }
                }
            }
        }

        stage('Docker Image Build') {
            steps {
                dir('product-service') {
                    sh "docker build -t ${env.DOCKER_IMAGE}:${env.DOCKER_TAG} ."
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh "docker rm -f ${env.DOCKER_IMAGE} || true"
                    sh """
                        docker run -d --name ${env.DOCKER_IMAGE} \
                        --network ${env.MY_NETWORK} \
                        -e SPRING_PROFILES_ACTIVE=prod \
                        -e SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888 \
                        ${env.DOCKER_IMAGE}:${env.DOCKER_TAG}
                    """
                }
            }
        }
    }
}