pipeline {
    agent any

    environment {
        MY_NETWORK = "buynest-network"
        DOCKER_HUB_ID = "minsik2434"
        DOCKER_IMAGE = "${DOCKER_HUB_ID}/docs-service"
        DOCKER_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Fetch API Spec') {
            steps {
                script {
                    echo "서비스 API 스펙 Fetch"
                    copyArtifacts projectName: 'buynest-user',
                    selector: lastSuccessful(),
                    filter: 'build/api-spec/*.json',
                    target: 'docs-service/static/specs/',
                    flatten: true
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                dir('docs-service') {
                    echo "docs 이미지 빌드"
                    sh "docker build -t ${env.DOCKER_IMAGE}:${env.DOCKER_TAG} ."

                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', passwordVariable: 'DOCKER_PW', usernameVariable: 'DOCKER_ID')]) {
                        sh "echo \$DOCKER_PW | docker login -u \$DOCKER_ID --password-stdin"
                        sh "docker push ${env.DOCKER_IMAGE}:${env.DOCKER_TAG}"
                    }   
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('docs-service') {    
                    echo "배포"
                    sh """
                        ansible-playbook -i ../ansible/inventory.ini ../ansible/deploy.yml \
                        -e target_service=docs-service
                    """
                }
            }
        }
    }
}