pipeline {
    agent any

    environment {
        MY_NETWORK = "buynest-network"
        DOCKER_HUB_ID = "minsik2434"
        DOCKER_IMAGE = "${DOCKER_HUB_ID}/user-service"
        DOCKER_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            agent {
                docker {
                    image 'eclipse-temurin:21-jdk'
                    args '-v /var/run/docker.sock:/var/run/docker.sock --network host'
                    reuseNode true
                }
            }
            steps {
                dir('user-service') {
                    script {
                        env.TESTCONTAINERS_HOST_OVERRIDE = "localhost"
                        env.TESTCONTAINERS_RYUK_DISABLED = "true"
                        sh "chmod +x gradlew"
                        sh "./gradlew clean build"
                        archiveArtifacts artifacts: 'build/api-spec/*.json', allowEmptyArchive: false
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('user-service') {
                    echo "Docker 이미지 빌드"
                    sh "docker build -t ${env.DOCKER_IMAGE}:${env.DOCKER_TAG} ."

                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', passwordVariable: 'DOCKER_PW', usernameVariable: 'DOCKER_ID')]) {
                        sh "echo \$DOCKER_PW | docker login -u \$DOCKER_ID --password-stdin"
                        sh "docker push ${env.DOCKER_IMAGE}:${env.DOCKER_TAG}"
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('user-service') {
                    echo "배포 준비"
                    sh """
                        echo "SPRING_PROFILES_ACTIVE=prod" > .env
                        echo "SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888" >> .env
                    """

                    echo "배포"
                    sh """
                        ansible-playbook -i ../infra/ansible/inventory.ini ../infra/ansible/deploy.yml \
                        -e target_service=user-service \
                        -e workspace=${env.WORKSPACE}
                    """
                }
            }
        }
    }
}