pipeline {
    agent any

    environment {
        MY_NETWORK = "buynest-network"
        DOCKER_IMAGE = "user-service"
        DOCKER_TAG = "latest"

        TESTCONTAINERS_RYUK_DISABLED = "true"
        TESTCONTAINERS_HOST_OVERRIDE = "host.docker.internal"
    }

    stages {
        stage('Prepare Network') {
            steps {
                sh "docker network create ${env.MY_NETWORK} || true"
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('user-service') {
                    echo "🚀 Testcontainers 출격! (Target IP: ${env.TESTCONTAINERS_HOST_OVERRIDE})"
                    sh "chmod +x gradlew"
                    sh "./gradlew clean build"
                }
            }
        }

        stage('Docker Image Build') {
            steps {
                dir('user-service') {
                    sh "docker build -t ${env.DOCKER_IMAGE}:${env.DOCKER_TAG} ."
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh "docker rm -f ${env.DOCKER_IMAGE} || true"
                    sh """
                        docker run -d --name ${env.DOCKER_IMAGE} \
                        --network ${env.MY_NETWORK} \
                        -e SPRING_PROFILES_ACTIVE=prod \
                        ${env.DOCKER_IMAGE}:${env.DOCKER_TAG}
                    """
                }
            }
        }

//         stage('Trigger Next') {
//             steps {
//                 echo 'User Service 배포 완료! Gateway를 호출합니다.'
//                 build job: 'buynest-api-gateway', wait: false
//             }
//         }
    }
}