pipeline {
    agent any

    environment {
        MY_NETWORK = "buynest-network"
        DOCKER_IMAGE = "user-service"
        DOCKER_TAG = "latest"
        TESTCONTAINERS_RYUK_DISABLED = "true"
        TESTCONTAINERS_HOST_OVERRIDE = "172.17.0.1"
    }

    stages {
        stage('Create Network') {
            steps {
                sh "docker network create ${env.MY_NETWORK} || true"
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            agent {
                docker {
                    image 'eclipse-temurin:21-jdk'
                    args '-v /var/run/docker.sock:/var/run/docker.sock --network host'
                    reuseNode true
                }
            }
            steps {
                dir('user-service') {
                    env.TESTCONTAINERS_HOST_OVERRIDE = "localhost"
                    env.TESTCONTAINERS_RYUK_DISABLED = "true"
                    echo "🚀 [필살기] 호스트 네트워크를 직접 사용하여 Testcontainers에 접속합니다!"
                    sh "chmod +x gradlew"
                    sh "./gradlew clean build"
                }
            }
        }

        stage('Image Build') {
            steps {
                dir('user-service') {
                    sh "docker build -t ${env.DOCKER_IMAGE}:${env.DOCKER_TAG} ."
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh "docker rm -f ${env.DOCKER_IMAGE} || true"
                    sh """
                        docker run -d --name ${env.DOCKER_IMAGE} \
                        --network ${env.MY_NETWORK} \
                        -e SPRING_PROFILES_ACTIVE=prod \
                        ${env.DOCKER_IMAGE}:${env.DOCKER_TAG}
                    """
                }
            }
        }
    }
}