pipeline {
    agent any

    environment {
        MY_NETWORK = "buynest-network"
        DOCKER_HUB_ID = "minsik2434"
        DOCKER_IMAGE = "${DOCKER_HUB_ID}/gateway-service"
        DOCKER_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('gateway-service') {
                    echo "빌드 시작"
                    sh "chmod +x gradlew"
                    sh "./gradlew clean build -x test"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('gateway-service') {
                    echo "docker Image 빌드"
                    sh "docker build -t ${env.DOCKER_IMAGE}:${env.DOCKER_TAG} ."

                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', passwordVariable: 'DOCKER_PW', usernameVariable: 'DOCKER_ID')]) {
                        sh "echo \$DOCKER_PW | docker login -u \$DOCKER_ID --password-stdin"
                        sh "docker push ${env.DOCKER_IMAGE}:${env.DOCKER_TAG}"
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('gateway-service') {
                    echo "배포 준비"
                    sh """
                        echo "SPRING_PROFILES_ACTIVE=prod" > .env
                        echo "SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888" >> .env
                    """

                    echo "배포"
                    sh """
                        ansible-playbook -i ../infra/ansible/inventory.ini ../infra/ansible/deploy-basic.yml \
                        -e target_service=gateway-service \
                        -e workspace=${env.WORKSPACE}
                    """
                }
            }
        }
    }
}