pipeline {
    agent any

    environment {
        MY_NETWORK = "buynest-network"
        DOCKER_IMAGE = "gateway-service"
        DOCKER_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('gateway-service') {
                    echo "빌드 시작"
                    sh "chmod +x gradlew"
                    sh "./gradlew clean build -x test"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('gateway-service') {
                    echo "docker Image 빌드"
                    sh "docker build -t ${env.DOCKER_IMAGE}:${env.DOCKER_TAG} ."
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo "배포 시작"
                    sh "docker rm -f ${env.DOCKER_IMAGE} || true"
                    sh """
                        docker run -d --name ${env.DOCKER_IMAGE} \
                        --network ${env.MY_NETWORK} \
                        -p 8000:8000 \
                        -e SPRING_PROFILES_ACTIVE=prod \
                        -e SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888 \
                        ${env.DOCKER_IMAGE}:${env.DOCKER_TAG}
                    """
                }
            }
        }
    }
}