const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '개요 (Intro)',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '01-intro',
        },
      ],
    },
    {
      type: 'category',
      label: '서비스 (Service)',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '02-services',
        },
      ],
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: '상품 서비스 (Product)',
      link: {
        type: 'generated-index',
        title: 'Product API',
        description: '상품 서비스 API 목록입니다.',
        slug: '/api-test',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/product',
        }
      ],
    },

    {
      type: 'category',
      label: '회원 서비스 (User)',
      link: { type: 'generated-index', title: 'User API', slug: '/category/user-api' },
      items: [
        { type: 'autogenerated', dirName: 'api/user' }
      ],
    },

    {
      type: 'category',
      label: '주문 서비스 (Order)',
      link: { type: 'generated-index', title: 'Order API', slug: '/order/user-api' },
      items: [
        { type: 'autogenerated', dirName: 'api/order' }
      ],
    },
  ],
};

export default sidebars;
