const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '개요 (Intro)',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '01-intro',
        },
      ],
    },
    {
      type: 'category',
      label: '서비스 (Service)',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '02-services',
        },
      ],
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: '상품 서비스 (Product)',
      link: {
        type: 'generated-index',
        title: 'Product API',
        description: '상품 서비스 API 목록입니다.',
        slug: '/api-test',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/product',
        }
      ],
    },
      // 나중에 주문(order), 회원(member) 서비스도 여기에 추가하면 됩니다.
  ],
};

export default sidebars;
