server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ecommerce-kubernetes/config.git
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
          default-label: main
          search-paths: /

encrypt:
  key-store:
    location: file:/app/keystore.jks
    alias: my-config-key
    secret: ${KEY_SECRET}